const pagesContent = {
  airBnBIntro: "Fun Cuba is active in 5 cities in Cuba (Havana, Viñales, Girón, Cienfuegos and Trinidad). Nevertheless we can provide hosting in other places if the client as for it. Cuba is not so small country as some people would think, there are more than 800 kms distance between Havana and Santiago de Cuba and the “highway” is in very bad shape. That is the reason we focus on a sector of the Island that we consider we can provide a reliable service, and that part would be the west of the country. If some clients wanna go further, we can also help even with suggestions (free) or booking rooms in those places. \n You can select the province in the field below and it will show the AirBnBs we work with, if that does not please your wishes, we could show you other choices. We strongly recommend these places coz those hosts are very nice and easy people and the houses meet all the requirements for you to fully enjoy holidays there.",
  chilling:
    "Chill out... just chill... this is what we are good at! We have thought in a number of stuff you can do while you are in Cuba. We focus in those fun stuff that for you as a foreigner is not so easy to achieve. For that we have a super pro crew, people who know “the streets”, that can make the  impossible, literally “pull a rabbit outa their ass”. \n This part is what really define Fun Cuba. This is the idea that drive us to put this project together. After year of experience in the tourist sector, we understand who poorly managed is tourism in Cuba. They focous on the beach or other natural resources. Those places are beautiful indeed and we hope you visit them when you come to the Island. But those places are not unique, you can find them anywhere else in the Caribbean. On top of that, the relation quality price is better in other places like Cancun and Punta Cana. Why would you go to Cuba then? The answer is the people. And it is an illusion the sell, the illusion that you will pay a full package with hotels, restauranst and tourist guidance already planned in advance, with a largo group or other tourists. Like that, you would approach to the real Cuba, just a fake and distorted image of the reality. If you want to know Cuba, you need to go out of the tourist route. It is a win-win. You as client will enjoy a rich and unique experience and at the same time, your money will contribute to empower Cuban people. That is why we don't use any state-owned services. Everything you pay, go directly to private business which are fundamental for the dynamic of the local economy.",
  tripPlan: {
    intro1:
      "Hey!!!... great you made it so far... This form will help you to plan your trip... no stress... it does not mean you are committing anything, you are not paying anything. Once you finish fill the form, then click the send button and we we'll get that form along with your email. We will contact you very soon and  then review the choices you made. ",
    intro2:
      "Only when we agree on all terms, them you, dear client, pay us and we set the machine in motion... remember Cuba is special place, it could specially bad or specially good... our staff makes mircales, literally pulling a rabbit outta ass in order to provide a very nice and unique experience in your visit to the Island",
  },
  home: {
    intro:
      "If you are looking for a place, quite, beautiful, with the best service and price, then do not go to Cuba, you probably won't find it there. Nevertheless, if you are kin in meeting new people, discover unique experiences, party like there is no tomorrow, enjoy beautiful natural places and beaches that are not crowded by tourists... you must have Cuba in your travel list! Cuba could be specially good or especially bad. Fun Cuba makes sures that everything runs smoothly. We provide 4 main services:",
    tooltipAirB:
      "Check Airbnb section for “casas particulares” (Air B&Bs). These are the best combination of cool host, best price and service. At the moment we our staff is located in Havana, Viñales, Girón, Cienfuegos and Trinidad nevertheless if are able to arrange book AirB&Bs in other cities ... we are super flexible so do not doubt to reach us... even if you won´t get our service and just need suggestions.",
    tooltipTaxi:
      "Taxi service between destinations. That you can book it ahead. Our people there can also help you to find local transportation.",
    tooltipGuidance:
      "You can reach us if you need recommendations on places to go like restaurants and nightclubs. Our staff has vast experience. Tips is a plus, you get it for free!",
    tooltipChill:
      "Chill Out is what defines the project. We have thought of a number of cool activities for you to do. Most of them you can not find anywhere else in Cuba, at least a reliable service. This will allow us to discover “Deep Cuba”. Go ahead and take a look in the section we have for this purpose. You'll thank us later. Don't forget to leave a review!",
    tripExplanation:
      "Trip section is a form that helps you to plan your trip, once you fill it, click the send button, you'll get an email with the copy of your planned trip and we'll get in contact with you right away. Then we finally discuss the details, agree on the terms. You pay us and we make the magic: dreamed vacations in Cuba. Feedback section is crucial for us. We thank you for putting time and energy to help us to improve ourselves.",
  },
};

export default pagesContent;
